language: python
cache: pip
python:
- '3.6'
matrix:
  include:
  - name: "Python 3.6 on Bionic Linux"
    python: 3.6
    dist: bionic
  - name: "Python 3.7 on Bionic Linux"
    python: 3.7
    dist: bionic
install:
- pip install -r requirements.txt -r requirements-test.txt
script:
- bash test.sh --noinstall --no-update --novirtualenv --strict --no-format
after_success:
- codecov
deploy:
  provider: pypi
  user: "radeklat"
  password:
    secure: teP7ISTqLk8mj7EC29Hvs+sfnkVbAF4yTwEV1QRw3M1ho6AtHB3GZMW6PG9+4GH9BtN2MEEsAoHL9XeDC3Gp4by1Fu89jcPZ5ylE99fmSRTmRrPpQpO5CayfWcE1rfvQeLON2KLRzzJYGRFqcAz/zprYAb9ZVyTASXYrDvVNBxah5zOYaUd9vYwaQKtOm5UBNgDCU3ncKtbs8WqB4/hM8QCNZsL6ScFNrDj7EKStufptOzn65TkdpIHbj8fpohXLztI2tIQQC7lVd/bT9cwCyuRHNpzn6jaaX91WMi4LEsU3PsayFkNhj/TxlQl3+JLH14vsT3MG+OHAtkA7h9DntaQ6Xy8j04jkR5gkZBllJcpLL5d9qsyA62hsU1e0cLqpGL7gMbmNfDIPM871PykvaSCNclpPmFTU3fjbxGD0xGuofhczfsPV6o7alusKRyxnI2DxdKGAnOMSc4PfJXhVSLImcSDDkLeOHgtT92O6tBlgJhobkNNOfHRiPvmTljK2hGwrOSSHg7jKUDbJUS7TsVcYl8OtglBIP/lqjnpnysxb3iN5PaCWBv/jx3lkfrIDANJ8VyMhJM8DfmKobqZya7zLYhjl6VdH1IUuLYQwqidHiJ0kPt/BfwEgfeau9cY3AHYbL2ochhBbD9TARxXI24BNzNmMcwCkbYs/hLU/H+w=
  on:
    branch: master
  skip_existing: true