language: python
cache: pip
python:
- '3.6'
matrix:
  include:
  - name: Python 3.6 on Bionic Linux
    python: 3.6
    dist: bionic
  - name: Python 3.7 on Bionic Linux
    python: 3.7
    dist: bionic
install:
- pip install -r requirements.txt -r requirements-test.txt
script:
- bash test.sh --noinstall --no-update --novirtualenv --strict --no-format
after_success:
- codecov
deploy:
  provider: pypi
  user: radeklat
  password:
    secure: jfXXh5dtSthIIWIIg0oup+Ehgzeq6ZEon8Ac5kReb+8sS54gDCQ0R2+27UmOQ6C/hECfmjeEbm8SSNEyZkmLcUxiJFQEVllKaqEdktpAEEEEMQHfxPJH45PwFFgw3UWqFcA/EePW2CcpyKNYyKg3eBJW9CD/5ChJtuxFvWkEDICz3uiex3shrJO6kM3Jvw+IoQwJfKJEcrSbzoWq3w/jIZZEGbQcv2+O94PO0k1Hn1YRvcobg7fNwfbw9AcxrZkCL+Bhj8C7+RjwHFAIZpdEgNjdqnO6JAqQLwU89ZzdwIQY1Jz8S6mIIgIMO0DBfuB4JHpVGQ1H3WQ710n2fV41tVMJmw+rjNgNov/3nfhzdIn5jYO+fkH/pOng9HriRcS+8CtOZE7oOtR67qp31/WKDwNPgd3pOcbqMUjvGT2xovQMGWAWZYIb//NqNFEMozLMmjpC//nCvsrw0WAg8UKjV6q5MJ4J0IRa1kKYkXbchoEw3bn0zzTo2CLJCxR+3rZ4Z1++/nB9JHGIfxkNJvJKjG74p19iy7VtXdnc93Clh5ToKtUVXhbSF7/wc39Q2F3Ogd+mWXx98IAqZYmMOEnM5etj2OFtrocyujIfzdTSYlU6tJbLve5h/JSKBQszntpszAlOK2tgPjTm5fffNbUHe1xINjMmqwkaZOg0kRTs4dk=
  on:
    branch: master
  skip_existing: true
